apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-detector
  namespace: ml-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drift-detector
  template:
    metadata:
      labels:
        app: drift-detector
    spec:
      containers:
        - name: drift-detector
          image: ghcr.io/ORG/enterprise-sec-ml/drift-detector:latest
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"